### ISSUE TITLE
Vscode css

### ISSUE THREAD

**Issue by Roblex09** [DimitrisMilonopoulos/mitsugen#11]
May I ask how did you apply the custom css theme to vscode?

**Comment by DimitrisMilonopoulos** [comment]
Hey of course,

here is the extension used: https://marketplace.visualstudio.com/items?itemName=be5invis.vscode-custom-css

You will need to follow the installation instructions for the extension depending on your platform. As this patches the css of vscode you will need to reinstall the extension on every vscode update.

**Comment by Roblex09** [comment]
Thank you!<3

One more question: Why yours doesnt have a title bar?

**Comment by DimitrisMilonopoulos** [comment]
It's a vscode option. In VSCode settings go to `Title Bar Style` and set it to `custom`.

**Comment by Roblex09** [comment]
Tysm!
