### ISSUE TITLE
GDM

### ISSUE THREAD

**Issue by Roblex09** [DimitrisMilonopoulos/mitsugen#12]
Hi,
Can you help with gdm theming?
I don't know what should I modify in the gnome-shell css file to make it look consistent with rest of the theme. I only want a blank screen no background, just matching color and panel.

**Comment by DimitrisMilonopoulos** [comment]
Hey,
looking into this, I could only find this utility which seems promising
https://github.com/gdm-settings/gdm-settings

Not sure if you can install themes that are installed on your home folder. 

Also it says that GDM might break when theming it.
https://github.com/gdm-settings/gdm-settings/issues/194

I would suggest using it with caution, if you want to.

**Comment by DimitrisMilonopoulos** [comment]
Hey,
looking into this, I could only find this utility which seems promising
https://github.com/gdm-settings/gdm-settings

Not sure if you can install themes that are installed on your home folder.

Also it says that GDM might break when theming it, but can be reinstalled in theory.
https://github.com/gdm-settings/gdm-settings/issues/194
I would suggest using it with caution, if you want to. But seems to be what you want! :)

**Comment by Roblex09** [comment]
It does not seem to work for me. I copied all the files to /usr/share/themes, applied the theme with gdm-tools, but still looks the same.
I use Ubuntu 23.04 btw

**Comment by DimitrisMilonopoulos** [comment]
What if you completely restart the computer?
Also once restarted maybe you can check if the tool has the newly applied theme selected.

**Comment by Roblex09** [comment]
Restarted it, but still looks the same.
![image](https://github.com/DimitrisMilonopoulos/mitsugen/assets/84228011/bd753c8f-0ca9-42bf-a54b-dd365dbebb31)

**Comment by Roblex09** [comment]
Even the default Yaru themes are not working.

**Comment by DimitrisMilonopoulos** [comment]
That's unfortunate :/

Maybe you can also check the `Top Bar` settings of the application. Reaching out to the application author could also be of help.

**Comment by Roblex09** [comment]
The AppImage version of gdm-tools fixed the issue.
Thank you for your help!
Have a nice day/night!
