### ISSUE TITLE
no module named regex

### ISSUE THREAD

**Issue by gmankab** [DimitrisMilonopoulos/mitsugen#2]
![image](https://user-images.githubusercontent.com/73340745/236641819-81c65cbe-d025-48a1-b4fa-d32952cee202.png)
![image](https://user-images.githubusercontent.com/73340745/236641865-7a0ecf27-eaf2-4fce-990f-e15fc8bbc6df.png)
![image](https://user-images.githubusercontent.com/73340745/236641892-c4f4bfc7-baef-4d82-b6dd-d74c12660dc5.png)

**Comment by kostya-zero** [comment]
I already sent merge request at #1. Wait for repo author to review them.

**UPD**: You can fix it by removing `poetry.lock` file and run `poetry install` command again.

**Comment by gmankab** [comment]
thanks
