### ISSUE TITLE
  'Key "Mitsugen" does not exist.'

### ISSUE THREAD

**Issue by bennetthermanoff** [DimitrisMilonopoulos/mitsugen#3]
when installing dependencies, unable to find key "Mitsugen"

$poetry install
Installing dependencies from lock file

  NonExistentKey

  'Key "Mitsugen" does not exist.'

  at /usr/lib/python3.11/site-packages/tomlkit/container.py:650 in __getitem__
      646│             key = SingleKey(key)
      647│ 
      648│         idx = self._map.get(key, None)
      649│         if idx is None:
    → 650│             raise NonExistentKey(key)
      651│ 
      652│         if isinstance(idx, tuple):
      653│             # The item we are getting is an out of order table
      654│             # so we need a proxy to retrieve the proper objects

**Comment by kostya-zero** [comment]
Try to remove `poetry.lock` file. This should fix your problem.

**Comment by DimitrisMilonopoulos** [comment]
pushed some updates can you try again?

**Comment by DimitrisMilonopoulos** [comment]
Believe its closed as I did some fixes feel free to reopen
