### ISSUE TITLE
QT Theme support?

### ISSUE THREAD

**Issue by dajix350** [DimitrisMilonopoulos/mitsugen#4]
Since QT apps look so out of place on Gnome, could this also apply the colours to them?

**Comment by DimitrisMilonopoulos** [comment]
@IntoTheVoid-900 don't have enough knowledge on QT theming to do it. The templates folder though is free for anyone to expand either for their own personal needs (let's say a specific third party app) so if you have the knowledge for QT feel free to implement.

Not in the scope as I want to add more focus on Gnome for now, but feel free to re open if you have some leads on how this can be easily done.
