### ISSUE TITLE
No module found 'src'

### ISSUE THREAD

**Issue by Soutaisei** [DimitrisMilonopoulos/mitsugen#8]
Getting error when trying to run the command:

```
Traceback (most recent call last):
  File "/home/soutaisei/Documents/Repositories/mitsugen/src/main.py", line 6, in <module>
    from src.util import Config, Scheme, Theme, parse_arguments, reload_apps, set_wallpaper
ModuleNotFoundError: No module named 'src'

```

Unsure if its some recent change or I'm doing something wrong.
Could you please help me out?

**Comment by DimitrisMilonopoulos** [comment]
Can you pull again and try it out?

**Comment by Soutaisei** [comment]
Unfortunately still the same

**Comment by DimitrisMilonopoulos** [comment]
What is the command you are running and your working dir when running the script?

**Comment by Soutaisei** [comment]
I'm running whats suggested on the installation guide:

```
poetry run python src/main.py path/to/my/wallpaper
```

**Comment by arun54321** [comment]
I have to run `export PYTHONPATH="$PYTHONPATH:$PWD" `in shell before running mitsugen to fix this error.

**Comment by DimitrisMilonopoulos** [comment]
Fixed imports in previous MR. Please update your branches!
